<center><h2><strong><font color="blue">WFH 2024 idBigData - Ilustrasi Sederhana SA di Transformer</font></strong></h2></center>

<img alt="" src="images/covers/cover_taudata_uin.jpg"/>

In [2]:
import warnings; warnings.simplefilter('ignore')
import numpy as np
from numpy import array
from numpy import random
from scipy.special import softmax

seed = 0
np.random.seed(seed)
random.seed(seed)
"Done"

'Done'

In [3]:
# defining word embeddings of 4 words
word_1_em = array([1, 1, 0])
word_2_em = array([0, 1, 1])
word_3_em = array([1, 0, 1])
word_4_em = array([0, 0, 1])
# stacking all the words to get a single word matrix
words = np.stack((word_1_em, word_2_em, word_3_em, word_4_em))
print(words)

[[1 1 0]
 [0 1 1]
 [1 0 1]
 [0 0 1]]


In [6]:
# randomly initialize the weight matrices for queries, keys, and values
W_Q = random.randint(3, size=(3, 3))
W_K = random.randint(3, size=(3, 3))
W_V = random.randint(3, size=(3, 3))
# generating the query, key, and value matrices
Q = words @ W_Q
K = words @ W_K
V = words @ W_V
# calculating the scores for the queries against all key vectors
scores = Q @ K.transpose()
# computing the weights using softmax operation
weights = softmax(scores / K.shape[1] ** 0.5, axis=1)
# computing the attention by a weighted sum of the value vectors
attention = weights @ V
print(attention)

[[1.99731342 1.54191758 0.        ]
 [1.9988959  1.65596787 0.        ]
 [1.97474746 1.88251929 0.        ]
 [1.93438951 1.85742362 0.        ]]
